export const genres = [
  {
    id: 28,
    color: '#8d99ae',
    nameSearch: 'acao',
    name: 'Ação',
  },
  {
    id: 12,
    color: '#2b2d42',
    nameSearch: 'aventura',
    name: 'Aventura',
  },
  {
    id: 27,
    color: '#',
    nameSearch: 'terror',
    name: 'Terror',
  },
  {
    id: 16,
    color: '#1944d8',
    nameSearch: 'animacao',
    name: 'Animação',
  },
  {
    id: 80,
    color: '#',
    nameSearch: 'crime',
    name: 'Crime',
  },
  {
    id: 99,
    color: '#',
    nameSearch: 'documentario',
    name: 'Documentário',
  },
  {
    id: 18,
    color: '#',
    nameSearch: 'drama',
    name: 'Drama',
  },
  {
    id: 35,
    color: '#58355e',
    nameSearch: 'comedia',
    name: 'Comédia',
  },
  {
    id: 10751,
    color: '#',
    nameSearch: 'familia',
    name: 'Família',
  },
  {
    id: 14,
    color: '#',
    nameSearch: 'fantasia',
    name: 'Fantasia',
  },
  {
    id: 53,
    color: '#',
    nameSearch: 'thriller',
    name: 'Thriller',
  },
  {
    id: 36,
    color: '#',
    nameSearch: 'historia',
    name: 'História',
  },
  {
    id: 10402,
    color: '#',
    nameSearch: 'musica',
    name: 'Música',
  },
  {
    id: 9648,
    color: '#',
    nameSearch: 'misterio',
    name: 'Mistério',
  },
  {
    id: 10752,
    color: '#',
    nameSearch: 'guerra',
    name: 'Guerra',
  },
  {
    id: 10770,
    color: '#',
    nameSearch: 'cinema tv',
    name: 'Cinema TV',
  },
  {
    id: 37,
    color: '#',
    nameSearch: 'faroeste',
    name: 'Faroeste',
  },
  {
    id: 10749,
    color: '#',
    nameSearch: 'romance',
    name: 'Romance',
  },
  {
    id: 878,
    color: '#',
    nameSearch: 'ficcao cientifica',
    name: 'Ficção Científica',
  },
];
